version: '3.8'
services:
  stats-server:
    build: stats
    image: stats
    container_name: explore-with-me-stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
      - ewm-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: explore-with-me-stats-postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: "stats"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"

  ewm-service:
    build: main
    image: ewm
    container_name: explore-with-me-ewm
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm

  ewm-db:
    image: postgres:14-alpine
    container_name: explore-with-me-postgres
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: "ewm"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"